package org.lasersonlab.anndata

import org.lasersonlab.zarr.untyped.Struct

package object loom {
  type Obs = Struct
}

/*
       [
            "index",
            "<i8"
        ],
        [
            "Age",
            "|i1"
        ],
        [
            "AnalysisPool",
            "|i1"
        ],
        [
            "AnalysisProject",
            "|i1"
        ],
        [
            "Bucket",
            "|i1"
        ],
        [
            "CellConc",
            "|i1"
        ],
        [
            "CellID",
            "|S24"
        ],
        [
            "Cell_Conc",
            "|i1"
        ],
        [
            "ChipID",
            "|i1"
        ],
        [
            "Class",
            "|i1"
        ],
        [
            "ClassProbability_Astrocyte",
            "<f8"
        ],
        [
            "ClassProbability_Astrocyte,Immune",
            "<f8"
        ],
        [
            "ClassProbability_Astrocyte,Neurons",
            "<f8"
        ],
        [
            "ClassProbability_Astrocyte,Oligos",
            "<f8"
        ],
        [
            "ClassProbability_Astrocyte,Vascular",
            "<f8"
        ],
        [
            "ClassProbability_Bergmann-glia",
            "<f8"
        ],
        [
            "ClassProbability_Blood",
            "<f8"
        ],
        [
            "ClassProbability_Blood,Vascular",
            "<f8"
        ],
        [
            "ClassProbability_Enteric-glia",
            "<f8"
        ],
        [
            "ClassProbability_Enteric-glia,Cycling",
            "<f8"
        ],
        [
            "ClassProbability_Ependymal",
            "<f8"
        ],
        [
            "ClassProbability_Ex-Neurons",
            "<f8"
        ],
        [
            "ClassProbability_Ex-Vascular",
            "<f8"
        ],
        [
            "ClassProbability_Immune",
            "<f8"
        ],
        [
            "ClassProbability_Immune,Neurons",
            "<f8"
        ],
        [
            "ClassProbability_Immune,Oligos",
            "<f8"
        ],
        [
            "ClassProbability_Neurons",
            "<f8"
        ],
        [
            "ClassProbability_Neurons,Cycling",
            "<f8"
        ],
        [
            "ClassProbability_Neurons,Oligos",
            "<f8"
        ],
        [
            "ClassProbability_Neurons,Satellite-glia",
            "<f8"
        ],
        [
            "ClassProbability_Neurons,Vascular",
            "<f8"
        ],
        [
            "ClassProbability_OEC",
            "<f8"
        ],
        [
            "ClassProbability_Oligos",
            "<f8"
        ],
        [
            "ClassProbability_Oligos,Cycling",
            "<f8"
        ],
        [
            "ClassProbability_Oligos,Vascular",
            "<f8"
        ],
        [
            "ClassProbability_Satellite-glia",
            "<f8"
        ],
        [
            "ClassProbability_Satellite-glia,Cycling",
            "<f8"
        ],
        [
            "ClassProbability_Satellite-glia,Schwann",
            "<f8"
        ],
        [
            "ClassProbability_Schwann",
            "<f8"
        ],
        [
            "ClassProbability_Ttr",
            "<f8"
        ],
        [
            "ClassProbability_Vascular",
            "<f8"
        ],
        [
            "ClusterName",
            "|i1"
        ],
        [
            "Clusters",
            "<i8"
        ],
        [
            "Comment",
            "|i1"
        ],
        [
            "Comments",
            "|i1"
        ],
        [
            "DateCaptured",
            "|i1"
        ],
        [
            "Date_Captured",
            "|i1"
        ],
        [
            "Description",
            "|i1"
        ],
        [
            "Developmental_compartment",
            "|i1"
        ],
        [
            "DonorID",
            "|i1"
        ],
        [
            "Estimated Number of Cells",
            "|i1"
        ],
        [
            "Flowcell",
            "|i1"
        ],
        [
            "Fraction Reads in Cells",
            "|i1"
        ],
        [
            "Label",
            "|i1"
        ],
        [
            "LeafOrder",
            "<i8"
        ],
        [
            "Location_based_on",
            "|i1"
        ],
        [
            "Mean Reads per Cell",
            "|i1"
        ],
        [
            "Median Genes per Cell",
            "|i1"
        ],
        [
            "Median UMI Counts per Cell",
            "|i1"
        ],
        [
            "MitoRiboRatio",
            "<f4"
        ],
        [
            "NGI_PlateWell",
            "|i1"
        ],
        [
            "Neurotransmitter",
            "|i1"
        ],
        [
            "NumPooledAnimals",
            "|i1"
        ],
        [
            "Num_Pooled_Animals",
            "|i1"
        ],
        [
            "Number of Reads",
            "|i1"
        ],
        [
            "OriginalClusters",
            "<i8"
        ],
        [
            "Outliers",
            "<i8"
        ],
        [
            "PCRCycles",
            "|i1"
        ],
        [
            "PCR_Cycles",
            "|i1"
        ],
        [
            "PassedQC",
            "|i1"
        ],
        [
            "PlugDate",
            "|i1"
        ],
        [
            "Plug_Date",
            "|i1"
        ],
        [
            "Probable_location",
            "|i1"
        ],
        [
            "Project",
            "|i1"
        ],
        [
            "Q30 Bases in Barcode",
            "|i1"
        ],
        [
            "Q30 Bases in RNA Read",
            "|i1"
        ],
        [
            "Q30 Bases in Sample Index",
            "|i1"
        ],
        [
            "Q30 Bases in UMI",
            "|i1"
        ],
        [
            "Reads Mapped Confidently to Exonic Regions",
            "|i1"
        ],
        [
            "Reads Mapped Confidently to Intergenic Regions",
            "|i1"
        ],
        [
            "Reads Mapped Confidently to Intronic Regions",
            "|i1"
        ],
        [
            "Reads Mapped Confidently to Transcriptome",
            "|i1"
        ],
        [
            "Region",
            "|i1"
        ],
        [
            "SampleID",
            "|i1"
        ],
        [
            "SampleIndex",
            "|i1"
        ],
        [
            "SampleOK",
            "|i1"
        ],
        [
            "Sample_Index",
            "|i1"
        ],
        [
            "SeqComment",
            "|i1"
        ],
        [
            "SeqLibDate",
            "|i1"
        ],
        [
            "SeqLibOk",
            "|i1"
        ],
        [
            "Seq_Comment",
            "|i1"
        ],
        [
            "Seq_Lib_Date",
            "|i1"
        ],
        [
            "Seq_Lib_Ok",
            "|i1"
        ],
        [
            "Sequencing Saturation",
            "|i1"
        ],
        [
            "Serial_Number",
            "|i1"
        ],
        [
            "Sex",
            "|i1"
        ],
        [
            "Species",
            "|i1"
        ],
        [
            "Strain",
            "|i1"
        ],
        [
            "Subclass",
            "|i1"
        ],
        [
            "TargetNumCells",
            "|i1"
        ],
        [
            "Target_Num_Cells",
            "|i1"
        ],
        [
            "TaxonomyRank1",
            "|i1"
        ],
        [
            "TaxonomyRank2",
            "|i1"
        ],
        [
            "TaxonomyRank3",
            "|i1"
        ],
        [
            "TaxonomyRank4",
            "|i1"
        ],
        [
            "TaxonomySymbol",
            "|i1"
        ],
        [
            "Taxonomy_group",
            "|i1"
        ],
        [
            "TimepointPool",
            "|i1"
        ],
        [
            "Tissue",
            "|i1"
        ],
        [
            "Total Genes Detected",
            "|i1"
        ],
        [
            "Transcriptome",
            "|i1"
        ],
        [
            "Valid Barcodes",
            "|i1"
        ],
        [
            "_KMeans_10",
            "<f8"
        ],
        [
            "_LogCV",
            "<f8"
        ],
        [
            "_LogMean",
            "<f8"
        ],
        [
            "_NGenes",
            "<f8"
        ],
        [
            "_PC1",
            "<f8"
        ],
        [
            "_PC2",
            "<f8"
        ],
        [
            "_Total",
            "<f8"
        ],
        [
            "_Valid",
            "<i8"
        ],
        [
            "_X",
            "<f8"
        ],
        [
            "_Y",
            "<f8"
        ],
        [
            "_tSNE1",
            "<f8"
        ],
        [
            "_tSNE2",
            "<f8"
        ],
        [
            "cDNAConcNanogramPerMicroliter",
            "|i1"
        ],
        [
            "cDNALibOk",
            "|i1"
        ],
        [
            "cDNA_Lib_Ok",
            "|i1"
        ],
        [
            "ngperul_cDNA",
            "|i1"
        ]
 */
